In [ ]:
# Given the following confusion matrix, evaluate (by hand) the model's performance.


# |               | pred dog   | pred cat   |
# |:------------  |-----------:|-----------:|
# | actual dog    |         46 |         7  |
# | actual cat    |         13 |         34 |
# In the context of this problem, what is a false positive?
# In the context of this problem, what is a false negative?
# How would you describe this model?

In [ ]:
# In the context of this problem, what is a false positive?
#predicted dog, actual cat

In [ ]:
# In the context of this problem, what is a false negative?
#predicted cat, actual dog

In [ ]:
# How would you describe this model?
#As a crosstab confusion_matrix

In [ ]:
# You are working as a datascientist working for Codeup Cody Creator (C3 for short), a rubber-duck manufacturing plant.

# Unfortunately, some of the rubber ducks that are produced will have defects. Your team has built several models that try to 
# predict those defects, and the data from their predictions can be found here.

# Use the predictions dataset and pandas to help answer the following questions:

# An internal team wants to investigate the cause of the manufacturing defects. They tell you that they want to identify as 
# many of the ducks that have a defect as possible. Which evaluation metric would be appropriate here? Which model would be 
# the best fit for this use case?
# Recently several stories in the local news have come out highlighting customers who received a rubber duck with a defect, 
# and portraying C3 in a bad light. The PR team has decided to launch a program that gives customers with a defective duck a 
# vacation to Hawaii. They need you to predict which ducks will have defects, but tell you the really don't want to 
# accidentally give out a vacation package when the duck really doesn't have a defect. Which evaluation metric would be 
# appropriate here? Which model would be the best fit for this use case?

In [48]:
import pandas as pd
import numpy as np
import os
import acquire
# visualize
import matplotlib.pyplot as plt
import seaborn as sns
plt.rc('figure', figsize=(8, 6))
plt.rc('font', size=13)


from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report


# turn off pink warning boxes
import warnings
warnings.filterwarnings("ignore")

# acquire
from env import host, user, password

In [7]:
df_c3 = pd.read_csv('c3.csv') 
df_c3.head()

actual     model1  model2     model3
0  No Defect  No Defect  Defect  No Defect
1  No Defect  No Defect  Defect     Defect
2  No Defect  No Defect  Defect  No Defect
3  No Defect     Defect  Defect     Defect
4  No Defect  No Defect  Defect  No Defect

In [32]:
df_c3.actual.value_counts()

No Defect    184
Defect        16
Name: actual, dtype: int64

In [ ]:
# An internal team wants to investigate the cause of the manufacturing defects. They tell you that they want to identify as 
# many of the ducks that have a defect as possible. Which evaluation metric would be appropriate here? Which model would be 
# the best fit for this use case?

In [ ]:
#precision = TP/TP+FP

In [ ]:
# Recently several stories in the local news have come out highlighting customers who received a rubber duck with a defect, 
# and portraying C3 in a bad light. The PR team has decided to launch a program that gives customers with a defective duck a 
# vacation to Hawaii. They need you to predict which ducks will have defects, but tell you the really don't want to 
# accidentally give out a vacation package when the duck really doesn't have a defect. Which evaluation metric would be 
# appropriate here? Which model would be the best fit for this use case?

In [ ]:
#recall = TP/TP+FN

In [16]:
df_c3['actual']== 'No Defect'

0       True
1       True
2       True
3       True
4       True
       ...  
195     True
196    False
197     True
198     True
199     True
Name: actual, Length: 200, dtype: bool

In [21]:
df_model1 = pd.crosstab(df_c3.actual, df_c3.model1)
df_model1

model1     Defect  No Defect
actual                      
Defect          8          8
No Defect       2        182

In [22]:
df_model2 = pd.crosstab(df_c3.actual, df_c3.model2)
df_model2

model2     Defect  No Defect
actual                      
Defect          9          7
No Defect      81        103

In [23]:
df_model3 = pd.crosstab(df_c3.actual, df_c3.model3)
df_model3

model3     Defect  No Defect
actual                      
Defect         13          3
No Defect      86         98

In [37]:
df_c3.model1.value_counts(), df_c3.model2.value_counts(), df_c3.model3.value_counts()

(No Defect    190
 Defect        10
 Name: model1, dtype: int64,
 No Defect    110
 Defect        90
 Name: model2, dtype: int64,
 No Defect    101
 Defect        99
 Name: model3, dtype: int64)

In [ ]:
# best model would be model 1

In [34]:
df_c3['baseline_pred'] = 'Defect'
df_c3

actual     model1     model2     model3 baseline_pred
0    No Defect  No Defect     Defect  No Defect        Defect
1    No Defect  No Defect     Defect     Defect        Defect
2    No Defect  No Defect     Defect  No Defect        Defect
3    No Defect     Defect     Defect     Defect        Defect
4    No Defect  No Defect     Defect  No Defect        Defect
..         ...        ...        ...        ...           ...
195  No Defect  No Defect     Defect     Defect        Defect
196     Defect     Defect  No Defect  No Defect        Defect
197  No Defect  No Defect  No Defect  No Defect        Defect
198  No Defect  No Defect     Defect     Defect        Defect
199  No Defect  No Defect  No Defect     Defect        Defect

[200 rows x 5 columns]

In [36]:
model_accuracy = (df_c3.model1 == df_c3.actual).mean()
baseline_accuracy = (df_c3.baseline_pred == df_c3.actual).mean()

print(f'   model accuracy: {model_accuracy:.2%}')
print(f'baseline accuracy: {baseline_accuracy:.2%}')

   model accuracy: 95.00%
baseline accuracy: 8.00%


In [ ]:
#Recall is how well we do on actually positive cases. Here we'll 
# define positive as defect.
# subset the dataframe so that we are only looking at the 
# rows where we have the positive case.

# evaluate how well our model's predictions do.

In [39]:
subset = df_c3[df_c3.actual == 'Defect']
subset.head()

actual     model1     model2  model3 baseline_pred
13  Defect  No Defect     Defect  Defect        Defect
30  Defect     Defect  No Defect  Defect        Defect
65  Defect     Defect     Defect  Defect        Defect
70  Defect     Defect     Defect  Defect        Defect
74  Defect  No Defect  No Defect  Defect        Defect

In [41]:
model_recall = (subset.model1 == subset.actual).mean()
baseline_recall = (subset.baseline_pred == subset.actual).mean()

print(f'   model recall: {model_recall:.2%}')
print(f'baseline recall: {baseline_recall:.2%}')

   model recall: 50.00%
baseline recall: 100.00%


In [45]:
model_recall = (subset.model2 == subset.actual).mean()
baseline_recall = (subset.baseline_pred == subset.actual).mean()

print(f'   model recall: {model_recall:.2%}')
print(f'baseline recall: {baseline_recall:.2%}')

   model recall: 56.25%
baseline recall: 100.00%


In [44]:
model_recall = (subset.model3 == subset.actual).mean()
baseline_recall = (subset.baseline_pred == subset.actual).mean()

print(f'   model recall: {model_recall:.2%}')
print(f'baseline recall: {baseline_recall:.2%}')

   model recall: 81.25%
baseline recall: 100.00%


In [ ]:
#calculate precision.

# precision is based on the times that the model predicts the positive class.
# the predictions of our model and the baseline differ, we'll need to create 2 
# seperate subsets.

In [47]:
subset = df_c3[df_c3.model1 == 'Defect']
model_precision = (subset.model1 == subset.actual).mean()

subset = df_c3[df_c3.baseline_pred == 'Defect']
baseline_precision = (subset.baseline_pred == subset.actual).mean()

print(f'model precision: {model_precision:.2%}')
print(f'baseline precision: {baseline_precision:.2%}')

model precision: 80.00%
baseline precision: 8.00%


In [ ]:
#sklearn

In [49]:
y_true = df_c3.actual
y_pred1 = df_c3.model1
y_pred2 = df_c3.model2
y_pred3 = df_c3.model3

In [50]:
accuracy_score(y_true, y_pred1), accuracy_score(y_true, y_pred2), accuracy_score(y_true, y_pred3)

(0.95, 0.56, 0.555)

In [51]:
precision_score(y_true, y_pred1, labels = ['No Defect', 'Defect'], average = None), precision_score(y_true, y_pred2, labels = ['No Defect', 'Defect'], average = None), precision_score(y_true, y_pred3, labels = ['No Defect', 'Defect'], average = None)


(array([0.95789474, 0.8       ]),
 array([0.93636364, 0.1       ]),
 array([0.97029703, 0.13131313]))

In [52]:
recall_score(y_true, y_pred1, labels = ['No Defect', 'Defect'], average = None), recall_score(y_true, y_pred2, labels = ['No Defect', 'Defect'], average = None), recall_score(y_true, y_pred3, labels = ['No Defect', 'Defect'], average = None)


(array([0.98913043, 0.5       ]),
 array([0.55978261, 0.5625    ]),
 array([0.5326087, 0.8125   ]))

In [53]:
print(classification_report(y_true, y_pred3, labels = ['No Defect', 'Defect']))


              precision    recall  f1-score   support

   No Defect       0.97      0.53      0.69       184
      Defect       0.13      0.81      0.23        16

    accuracy                           0.56       200
   macro avg       0.55      0.67      0.46       200
weighted avg       0.90      0.56      0.65       200



In [ ]:
# Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?

#would use the precision metric, false pos would be costly, predict defect and actuality of none
#model1 has most true pos and fp which are counted for in precision

In [54]:
subseta1 = df_c3[df_c3.model1 == 'Defect']
subseta2 = df_c3[df_c3.model2 == 'Defect']
subseta3 = df_c3[df_c3.model3 == 'Defect']

In [57]:
model_precision = (subseta1.actual == subseta1.model1).mean()

print("Model 1")
print(f"Model precision: {model_precision:.2%}")

Model 1
Model precision: 80.00%


In [58]:
model_precision = (subseta2.actual == subseta2.model2).mean()

print("Model 1")
print(f"Model precision: {model_precision:.2%}")

Model 1
Model precision: 10.00%


In [59]:
model_precision = (subseta3.actual == subseta3.model3).mean()

print("Model 1")
print(f"Model precision: {model_precision:.2%}")

Model 1
Model precision: 13.13%


In [60]:
print(classification_report(y_true, y_pred1, labels = ['No Defect', 'Defect']))

              precision    recall  f1-score   support

   No Defect       0.96      0.99      0.97       184
      Defect       0.80      0.50      0.62        16

    accuracy                           0.95       200
   macro avg       0.88      0.74      0.79       200
weighted avg       0.95      0.95      0.94       200



In [ ]:
# # You are working as a data scientist for Gives You Paws ™, a subscription based service that shows you cute pictures of 
# dogs or cats (or both for an additional fee).

# # At Gives You Paws, anyone can upload pictures of their cats or dogs. The photos are then put through a two step process. 
# First an automated algorithm tags pictures as either a cat or a dog (Phase I). Next, the photos that have been initially 
# identified are put through another round of review, possibly with some human oversight, before being presented to the users 
# (Phase II).

# # Several models have already been developed with the data, and you can find their results here.

# # Given this dataset, use pandas to create a baseline model (i.e. a model that just predicts the most common class) 
# and answer the following questions:

# # In terms of accuracy, how do the various models compare to the baseline model? Are any of the models 
# better than the baseline?
# # Suppose you are working on a team that solely deals with dog pictures. Which of these models would you 
# recomend for Phase I? For Phase II?
# # Suppose you are working on a team that solely deals with cat pictures. Which of these models would you 
# recomend for Phase I? For Phase II?

In [62]:
df_paws = pd.read_csv('gives_you_paws.csv') 
df_paws.head()

actual model1 model2 model3 model4
0    cat    cat    dog    cat    dog
1    dog    dog    cat    cat    dog
2    dog    cat    cat    cat    dog
3    dog    dog    dog    cat    dog
4    cat    cat    cat    dog    dog

In [63]:
df_paws.actual.value_counts(),df_paws.model1.value_counts(),df_paws.model2.value_counts(),df_paws.model3.value_counts(),df_paws.model4.value_counts(),

(dog    3254
 cat    1746
 Name: actual, dtype: int64,
 dog    2937
 cat    2063
 Name: model1, dtype: int64,
 cat    3212
 dog    1788
 Name: model2, dtype: int64,
 dog    2508
 cat    2492
 Name: model3, dtype: int64,
 dog    4253
 cat     747
 Name: model4, dtype: int64)

In [65]:
df_paws['baseline_prediction'] = 'dog'
df_paws

actual model1 model2 model3 model4 baseline_prediction
0       cat    cat    dog    cat    dog                 dog
1       dog    dog    cat    cat    dog                 dog
2       dog    cat    cat    cat    dog                 dog
3       dog    dog    dog    cat    dog                 dog
4       cat    cat    cat    dog    dog                 dog
...     ...    ...    ...    ...    ...                 ...
4995    dog    dog    dog    dog    dog                 dog
4996    dog    dog    cat    cat    dog                 dog
4997    dog    cat    cat    dog    dog                 dog
4998    cat    cat    cat    cat    dog                 dog
4999    dog    dog    dog    dog    dog                 dog

[5000 rows x 6 columns]

In [25]:
df_modelone = pd.crosstab(df_paws.actual, df_paws.model1)
df_modelone

model1   cat   dog
actual            
cat     1423   323
dog      640  2614

In [26]:
df_modeltwo = pd.crosstab(df_paws.actual, df_paws.model2)
df_modeltwo

model2   cat   dog
actual            
cat     1555   191
dog     1657  1597

In [31]:
df_modelthree = pd.crosstab(df_paws.actual, df_paws.model3)
df_modelthree

model3   cat   dog
actual            
cat      893   853
dog     1599  1655

In [28]:
df_modelfour = pd.crosstab(df_paws.actual, df_paws.model4)
df_modelfour

model4  cat   dog
actual           
cat     603  1143
dog     144  3110

In [66]:
p_true = df_paws.actual
p_pred1 = df_paws.model1
p_pred2 = df_paws.model2
p_pred3 = df_paws.model3
p_pred4 = df_paws.model4

In [67]:
(df_paws.actual == df_paws.baseline_prediction).mean()

0.6508

In [ ]:
# # In terms of accuracy, how do the various models compare to the baseline model? Are any of the models 
# better than the baseline?


In [68]:
model_accuracy = (df_paws.actual == df_paws.model1).mean()
baseline_accuracy = (df_paws.actual == df_paws.baseline_prediction).mean()

print(f'   model accuracy: {model_accuracy:.2%}')
print(f'baseline accuracy: {baseline_accuracy:.2%}')

   model accuracy: 80.74%
baseline accuracy: 65.08%


In [69]:
model_accuracy = (df_paws.actual == df_paws.model2).mean()
baseline_accuracy = (df_paws.actual == df_paws.baseline_prediction).mean()

print(f'   model accuracy: {model_accuracy:.2%}')
print(f'baseline accuracy: {baseline_accuracy:.2%}')

   model accuracy: 63.04%
baseline accuracy: 65.08%


In [70]:
model_accuracy = (df_paws.actual == df_paws.model3).mean()
baseline_accuracy = (df_paws.actual == df_paws.baseline_prediction).mean()

print(f'   model accuracy: {model_accuracy:.2%}')
print(f'baseline accuracy: {baseline_accuracy:.2%}')

   model accuracy: 50.96%
baseline accuracy: 65.08%


In [71]:
model_accuracy = (df_paws.actual == df_paws.model4).mean()
baseline_accuracy = (df_paws.actual == df_paws.baseline_prediction).mean()

print(f'   model accuracy: {model_accuracy:.2%}')
print(f'baseline accuracy: {baseline_accuracy:.2%}')

   model accuracy: 74.26%
baseline accuracy: 65.08%


In [72]:
models = list(df_paws.columns)
models = models[1:]
models

['model1', 'model2', 'model3', 'model4', 'baseline_prediction']

In [75]:
# accuracy for for each model
output = {}
for model in models:
    accuracy = (df_paws.actual == df_paws[model]).mean()
    output.update({model:accuracy})
    
output

{'model1': 0.8074,
 'model2': 0.6304,
 'model3': 0.5096,
 'model4': 0.7426,
 'baseline_prediction': 0.6508}

In [76]:
pd.DataFrame(list(output.items()), columns = ['model', 'accuracy'])

model  accuracy
0               model1    0.8074
1               model2    0.6304
2               model3    0.5096
3               model4    0.7426
4  baseline_prediction    0.6508

In [ ]:
#Model 1 had a higher percentage, more true pos and true neg 


In [ ]:
# # Suppose you are working on a team that solely deals with dog pictures. Which of these models would you 
# recomend for Phase I? For Phase II?

# for:
# PHASE I: use recall on Model4 with a baseline of 'dog' as they correctly predicted dogs.
#          
#          Max dogs = minimizing FN
# PHASE II: Recall on Model2 with a baseline of 'cat' as they correctly predicted cats.
#           Here we can id & filter out the cat pics.


In [ ]:
# # Suppose you are working on a team that solely deals with cat pictures. Which of these models would you 
# recomend for Phase I? For Phase II?